name: Notification Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Notification Docker image
      run: docker build . --file Dockerfile --tag notification:$(date +%s)
